// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: cognobserve/v1/common.proto

package cognobservev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/structpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Span level for categorizing spans
type SpanLevel int32

const (
	SpanLevel_SPAN_LEVEL_UNSPECIFIED SpanLevel = 0
	SpanLevel_SPAN_LEVEL_DEBUG       SpanLevel = 1
	SpanLevel_SPAN_LEVEL_DEFAULT     SpanLevel = 2
	SpanLevel_SPAN_LEVEL_WARNING     SpanLevel = 3
	SpanLevel_SPAN_LEVEL_ERROR       SpanLevel = 4
)

// Enum value maps for SpanLevel.
var (
	SpanLevel_name = map[int32]string{
		0: "SPAN_LEVEL_UNSPECIFIED",
		1: "SPAN_LEVEL_DEBUG",
		2: "SPAN_LEVEL_DEFAULT",
		3: "SPAN_LEVEL_WARNING",
		4: "SPAN_LEVEL_ERROR",
	}
	SpanLevel_value = map[string]int32{
		"SPAN_LEVEL_UNSPECIFIED": 0,
		"SPAN_LEVEL_DEBUG":       1,
		"SPAN_LEVEL_DEFAULT":     2,
		"SPAN_LEVEL_WARNING":     3,
		"SPAN_LEVEL_ERROR":       4,
	}
)

func (x SpanLevel) Enum() *SpanLevel {
	p := new(SpanLevel)
	*p = x
	return p
}

func (x SpanLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SpanLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_cognobserve_v1_common_proto_enumTypes[0].Descriptor()
}

func (SpanLevel) Type() protoreflect.EnumType {
	return &file_cognobserve_v1_common_proto_enumTypes[0]
}

func (x SpanLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SpanLevel.Descriptor instead.
func (SpanLevel) EnumDescriptor() ([]byte, []int) {
	return file_cognobserve_v1_common_proto_rawDescGZIP(), []int{0}
}

// Token usage for LLM calls
type TokenUsage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens     *int32                 `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3,oneof" json:"prompt_tokens,omitempty"`
	CompletionTokens *int32                 `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3,oneof" json:"completion_tokens,omitempty"`
	TotalTokens      *int32                 `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3,oneof" json:"total_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TokenUsage) Reset() {
	*x = TokenUsage{}
	mi := &file_cognobserve_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUsage) ProtoMessage() {}

func (x *TokenUsage) ProtoReflect() protoreflect.Message {
	mi := &file_cognobserve_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUsage.ProtoReflect.Descriptor instead.
func (*TokenUsage) Descriptor() ([]byte, []int) {
	return file_cognobserve_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *TokenUsage) GetPromptTokens() int32 {
	if x != nil && x.PromptTokens != nil {
		return *x.PromptTokens
	}
	return 0
}

func (x *TokenUsage) GetCompletionTokens() int32 {
	if x != nil && x.CompletionTokens != nil {
		return *x.CompletionTokens
	}
	return 0
}

func (x *TokenUsage) GetTotalTokens() int32 {
	if x != nil && x.TotalTokens != nil {
		return *x.TotalTokens
	}
	return 0
}

var File_cognobserve_v1_common_proto protoreflect.FileDescriptor

const file_cognobserve_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1bcognobserve/v1/common.proto\x12\x0ecognobserve.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xc9\x01\n" +
	"\n" +
	"TokenUsage\x12(\n" +
	"\rprompt_tokens\x18\x01 \x01(\x05H\x00R\fpromptTokens\x88\x01\x01\x120\n" +
	"\x11completion_tokens\x18\x02 \x01(\x05H\x01R\x10completionTokens\x88\x01\x01\x12&\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05H\x02R\vtotalTokens\x88\x01\x01B\x10\n" +
	"\x0e_prompt_tokensB\x14\n" +
	"\x12_completion_tokensB\x0f\n" +
	"\r_total_tokens*\x83\x01\n" +
	"\tSpanLevel\x12\x1a\n" +
	"\x16SPAN_LEVEL_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10SPAN_LEVEL_DEBUG\x10\x01\x12\x16\n" +
	"\x12SPAN_LEVEL_DEFAULT\x10\x02\x12\x16\n" +
	"\x12SPAN_LEVEL_WARNING\x10\x03\x12\x14\n" +
	"\x10SPAN_LEVEL_ERROR\x10\x04B\xb6\x01\n" +
	"\x12com.cognobserve.v1B\vCommonProtoP\x01Z:github.com/cognobserve/ingest/internal/proto/cognobservev1\xa2\x02\x03CXX\xaa\x02\x0eCognobserve.V1\xca\x02\x0eCognobserve\\V1\xe2\x02\x1aCognobserve\\V1\\GPBMetadata\xea\x02\x0fCognobserve::V1b\x06proto3"

var (
	file_cognobserve_v1_common_proto_rawDescOnce sync.Once
	file_cognobserve_v1_common_proto_rawDescData []byte
)

func file_cognobserve_v1_common_proto_rawDescGZIP() []byte {
	file_cognobserve_v1_common_proto_rawDescOnce.Do(func() {
		file_cognobserve_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cognobserve_v1_common_proto_rawDesc), len(file_cognobserve_v1_common_proto_rawDesc)))
	})
	return file_cognobserve_v1_common_proto_rawDescData
}

var file_cognobserve_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cognobserve_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cognobserve_v1_common_proto_goTypes = []any{
	(SpanLevel)(0),     // 0: cognobserve.v1.SpanLevel
	(*TokenUsage)(nil), // 1: cognobserve.v1.TokenUsage
}
var file_cognobserve_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cognobserve_v1_common_proto_init() }
func file_cognobserve_v1_common_proto_init() {
	if File_cognobserve_v1_common_proto != nil {
		return
	}
	file_cognobserve_v1_common_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cognobserve_v1_common_proto_rawDesc), len(file_cognobserve_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cognobserve_v1_common_proto_goTypes,
		DependencyIndexes: file_cognobserve_v1_common_proto_depIdxs,
		EnumInfos:         file_cognobserve_v1_common_proto_enumTypes,
		MessageInfos:      file_cognobserve_v1_common_proto_msgTypes,
	}.Build()
	File_cognobserve_v1_common_proto = out.File
	file_cognobserve_v1_common_proto_goTypes = nil
	file_cognobserve_v1_common_proto_depIdxs = nil
}
