// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: cognobserve/v1/ingest.proto

package cognobservev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User information for tracking end-users
type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Email         *string                `protobuf:"bytes,2,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,3,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_cognobserve_v1_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cognobserve_v1_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_cognobserve_v1_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UserInfo) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Request to ingest a trace with spans
type IngestTraceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Trace information
	TraceId  *string          `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3,oneof" json:"trace_id,omitempty"` // Optional, server generates if not provided
	Name     string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Metadata *structpb.Struct `protobuf:"bytes,3,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	// Spans to ingest
	Spans []*IngestSpan `protobuf:"bytes,4,rep,name=spans,proto3" json:"spans,omitempty"`
	// Session tracking (for multi-turn conversations)
	SessionId *string `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3,oneof" json:"session_id,omitempty"`
	// User tracking (end-users of AI applications)
	UserId        *string   `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	User          *UserInfo `protobuf:"bytes,7,opt,name=user,proto3,oneof" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestTraceRequest) Reset() {
	*x = IngestTraceRequest{}
	mi := &file_cognobserve_v1_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestTraceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestTraceRequest) ProtoMessage() {}

func (x *IngestTraceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cognobserve_v1_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestTraceRequest.ProtoReflect.Descriptor instead.
func (*IngestTraceRequest) Descriptor() ([]byte, []int) {
	return file_cognobserve_v1_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *IngestTraceRequest) GetTraceId() string {
	if x != nil && x.TraceId != nil {
		return *x.TraceId
	}
	return ""
}

func (x *IngestTraceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IngestTraceRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *IngestTraceRequest) GetSpans() []*IngestSpan {
	if x != nil {
		return x.Spans
	}
	return nil
}

func (x *IngestTraceRequest) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *IngestTraceRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *IngestTraceRequest) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

// Span data for ingestion
type IngestSpan struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SpanId          *string                `protobuf:"bytes,1,opt,name=span_id,json=spanId,proto3,oneof" json:"span_id,omitempty"` // Optional, server generates if not provided
	ParentSpanId    *string                `protobuf:"bytes,2,opt,name=parent_span_id,json=parentSpanId,proto3,oneof" json:"parent_span_id,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	StartTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3,oneof" json:"end_time,omitempty"`
	Input           *structpb.Struct       `protobuf:"bytes,6,opt,name=input,proto3,oneof" json:"input,omitempty"`
	Output          *structpb.Struct       `protobuf:"bytes,7,opt,name=output,proto3,oneof" json:"output,omitempty"`
	Metadata        *structpb.Struct       `protobuf:"bytes,8,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	Model           *string                `protobuf:"bytes,9,opt,name=model,proto3,oneof" json:"model,omitempty"`
	ModelParameters *structpb.Struct       `protobuf:"bytes,10,opt,name=model_parameters,json=modelParameters,proto3,oneof" json:"model_parameters,omitempty"`
	Usage           *TokenUsage            `protobuf:"bytes,11,opt,name=usage,proto3,oneof" json:"usage,omitempty"`
	Level           SpanLevel              `protobuf:"varint,12,opt,name=level,proto3,enum=cognobserve.v1.SpanLevel" json:"level,omitempty"`
	StatusMessage   *string                `protobuf:"bytes,13,opt,name=status_message,json=statusMessage,proto3,oneof" json:"status_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IngestSpan) Reset() {
	*x = IngestSpan{}
	mi := &file_cognobserve_v1_ingest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestSpan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestSpan) ProtoMessage() {}

func (x *IngestSpan) ProtoReflect() protoreflect.Message {
	mi := &file_cognobserve_v1_ingest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestSpan.ProtoReflect.Descriptor instead.
func (*IngestSpan) Descriptor() ([]byte, []int) {
	return file_cognobserve_v1_ingest_proto_rawDescGZIP(), []int{2}
}

func (x *IngestSpan) GetSpanId() string {
	if x != nil && x.SpanId != nil {
		return *x.SpanId
	}
	return ""
}

func (x *IngestSpan) GetParentSpanId() string {
	if x != nil && x.ParentSpanId != nil {
		return *x.ParentSpanId
	}
	return ""
}

func (x *IngestSpan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IngestSpan) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *IngestSpan) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *IngestSpan) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *IngestSpan) GetOutput() *structpb.Struct {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *IngestSpan) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *IngestSpan) GetModel() string {
	if x != nil && x.Model != nil {
		return *x.Model
	}
	return ""
}

func (x *IngestSpan) GetModelParameters() *structpb.Struct {
	if x != nil {
		return x.ModelParameters
	}
	return nil
}

func (x *IngestSpan) GetUsage() *TokenUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *IngestSpan) GetLevel() SpanLevel {
	if x != nil {
		return x.Level
	}
	return SpanLevel_SPAN_LEVEL_UNSPECIFIED
}

func (x *IngestSpan) GetStatusMessage() string {
	if x != nil && x.StatusMessage != nil {
		return *x.StatusMessage
	}
	return ""
}

// Response after ingesting a trace
type IngestTraceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanIds       []string               `protobuf:"bytes,2,rep,name=span_ids,json=spanIds,proto3" json:"span_ids,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestTraceResponse) Reset() {
	*x = IngestTraceResponse{}
	mi := &file_cognobserve_v1_ingest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestTraceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestTraceResponse) ProtoMessage() {}

func (x *IngestTraceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cognobserve_v1_ingest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestTraceResponse.ProtoReflect.Descriptor instead.
func (*IngestTraceResponse) Descriptor() ([]byte, []int) {
	return file_cognobserve_v1_ingest_proto_rawDescGZIP(), []int{3}
}

func (x *IngestTraceResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *IngestTraceResponse) GetSpanIds() []string {
	if x != nil {
		return x.SpanIds
	}
	return nil
}

func (x *IngestTraceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Batch ingestion request
type IngestBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Traces        []*IngestTraceRequest  `protobuf:"bytes,1,rep,name=traces,proto3" json:"traces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestBatchRequest) Reset() {
	*x = IngestBatchRequest{}
	mi := &file_cognobserve_v1_ingest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestBatchRequest) ProtoMessage() {}

func (x *IngestBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cognobserve_v1_ingest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestBatchRequest.ProtoReflect.Descriptor instead.
func (*IngestBatchRequest) Descriptor() ([]byte, []int) {
	return file_cognobserve_v1_ingest_proto_rawDescGZIP(), []int{4}
}

func (x *IngestBatchRequest) GetTraces() []*IngestTraceRequest {
	if x != nil {
		return x.Traces
	}
	return nil
}

// Batch ingestion response
type IngestBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*IngestTraceResponse `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	SuccessCount  int32                  `protobuf:"varint,2,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	ErrorCount    int32                  `protobuf:"varint,3,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestBatchResponse) Reset() {
	*x = IngestBatchResponse{}
	mi := &file_cognobserve_v1_ingest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestBatchResponse) ProtoMessage() {}

func (x *IngestBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cognobserve_v1_ingest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestBatchResponse.ProtoReflect.Descriptor instead.
func (*IngestBatchResponse) Descriptor() ([]byte, []int) {
	return file_cognobserve_v1_ingest_proto_rawDescGZIP(), []int{5}
}

func (x *IngestBatchResponse) GetResults() []*IngestTraceResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *IngestBatchResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *IngestBatchResponse) GetErrorCount() int32 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

// Health check
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_cognobserve_v1_ingest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cognobserve_v1_ingest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_cognobserve_v1_ingest_proto_rawDescGZIP(), []int{6}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_cognobserve_v1_ingest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cognobserve_v1_ingest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_cognobserve_v1_ingest_proto_rawDescGZIP(), []int{7}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_cognobserve_v1_ingest_proto protoreflect.FileDescriptor

const file_cognobserve_v1_ingest_proto_rawDesc = "" +
	"\n" +
	"\x1bcognobserve/v1/ingest.proto\x12\x0ecognobserve.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bcognobserve/v1/common.proto\"\x98\x01\n" +
	"\bUserInfo\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x02 \x01(\tH\x01R\x05email\x88\x01\x01\x128\n" +
	"\bmetadata\x18\x03 \x01(\v2\x17.google.protobuf.StructH\x02R\bmetadata\x88\x01\x01B\a\n" +
	"\x05_nameB\b\n" +
	"\x06_emailB\v\n" +
	"\t_metadata\"\xe7\x02\n" +
	"\x12IngestTraceRequest\x12\x1e\n" +
	"\btrace_id\x18\x01 \x01(\tH\x00R\atraceId\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x128\n" +
	"\bmetadata\x18\x03 \x01(\v2\x17.google.protobuf.StructH\x01R\bmetadata\x88\x01\x01\x120\n" +
	"\x05spans\x18\x04 \x03(\v2\x1a.cognobserve.v1.IngestSpanR\x05spans\x12\"\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tH\x02R\tsessionId\x88\x01\x01\x12\x1c\n" +
	"\auser_id\x18\x06 \x01(\tH\x03R\x06userId\x88\x01\x01\x121\n" +
	"\x04user\x18\a \x01(\v2\x18.cognobserve.v1.UserInfoH\x04R\x04user\x88\x01\x01B\v\n" +
	"\t_trace_idB\v\n" +
	"\t_metadataB\r\n" +
	"\v_session_idB\n" +
	"\n" +
	"\b_user_idB\a\n" +
	"\x05_user\"\x86\x06\n" +
	"\n" +
	"IngestSpan\x12\x1c\n" +
	"\aspan_id\x18\x01 \x01(\tH\x00R\x06spanId\x88\x01\x01\x12)\n" +
	"\x0eparent_span_id\x18\x02 \x01(\tH\x01R\fparentSpanId\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12:\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\aendTime\x88\x01\x01\x122\n" +
	"\x05input\x18\x06 \x01(\v2\x17.google.protobuf.StructH\x03R\x05input\x88\x01\x01\x124\n" +
	"\x06output\x18\a \x01(\v2\x17.google.protobuf.StructH\x04R\x06output\x88\x01\x01\x128\n" +
	"\bmetadata\x18\b \x01(\v2\x17.google.protobuf.StructH\x05R\bmetadata\x88\x01\x01\x12\x19\n" +
	"\x05model\x18\t \x01(\tH\x06R\x05model\x88\x01\x01\x12G\n" +
	"\x10model_parameters\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructH\aR\x0fmodelParameters\x88\x01\x01\x125\n" +
	"\x05usage\x18\v \x01(\v2\x1a.cognobserve.v1.TokenUsageH\bR\x05usage\x88\x01\x01\x12/\n" +
	"\x05level\x18\f \x01(\x0e2\x19.cognobserve.v1.SpanLevelR\x05level\x12*\n" +
	"\x0estatus_message\x18\r \x01(\tH\tR\rstatusMessage\x88\x01\x01B\n" +
	"\n" +
	"\b_span_idB\x11\n" +
	"\x0f_parent_span_idB\v\n" +
	"\t_end_timeB\b\n" +
	"\x06_inputB\t\n" +
	"\a_outputB\v\n" +
	"\t_metadataB\b\n" +
	"\x06_modelB\x13\n" +
	"\x11_model_parametersB\b\n" +
	"\x06_usageB\x11\n" +
	"\x0f_status_message\"e\n" +
	"\x13IngestTraceResponse\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x19\n" +
	"\bspan_ids\x18\x02 \x03(\tR\aspanIds\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"P\n" +
	"\x12IngestBatchRequest\x12:\n" +
	"\x06traces\x18\x01 \x03(\v2\".cognobserve.v1.IngestTraceRequestR\x06traces\"\x9a\x01\n" +
	"\x13IngestBatchResponse\x12=\n" +
	"\aresults\x18\x01 \x03(\v2#.cognobserve.v1.IngestTraceResponseR\aresults\x12#\n" +
	"\rsuccess_count\x18\x02 \x01(\x05R\fsuccessCount\x12\x1f\n" +
	"\verror_count\x18\x03 \x01(\x05R\n" +
	"errorCount\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversionB\xb6\x01\n" +
	"\x12com.cognobserve.v1B\vIngestProtoP\x01Z:github.com/cognobserve/ingest/internal/proto/cognobservev1\xa2\x02\x03CXX\xaa\x02\x0eCognobserve.V1\xca\x02\x0eCognobserve\\V1\xe2\x02\x1aCognobserve\\V1\\GPBMetadata\xea\x02\x0fCognobserve::V1b\x06proto3"

var (
	file_cognobserve_v1_ingest_proto_rawDescOnce sync.Once
	file_cognobserve_v1_ingest_proto_rawDescData []byte
)

func file_cognobserve_v1_ingest_proto_rawDescGZIP() []byte {
	file_cognobserve_v1_ingest_proto_rawDescOnce.Do(func() {
		file_cognobserve_v1_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cognobserve_v1_ingest_proto_rawDesc), len(file_cognobserve_v1_ingest_proto_rawDesc)))
	})
	return file_cognobserve_v1_ingest_proto_rawDescData
}

var file_cognobserve_v1_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_cognobserve_v1_ingest_proto_goTypes = []any{
	(*UserInfo)(nil),              // 0: cognobserve.v1.UserInfo
	(*IngestTraceRequest)(nil),    // 1: cognobserve.v1.IngestTraceRequest
	(*IngestSpan)(nil),            // 2: cognobserve.v1.IngestSpan
	(*IngestTraceResponse)(nil),   // 3: cognobserve.v1.IngestTraceResponse
	(*IngestBatchRequest)(nil),    // 4: cognobserve.v1.IngestBatchRequest
	(*IngestBatchResponse)(nil),   // 5: cognobserve.v1.IngestBatchResponse
	(*HealthRequest)(nil),         // 6: cognobserve.v1.HealthRequest
	(*HealthResponse)(nil),        // 7: cognobserve.v1.HealthResponse
	(*structpb.Struct)(nil),       // 8: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
	(*TokenUsage)(nil),            // 10: cognobserve.v1.TokenUsage
	(SpanLevel)(0),                // 11: cognobserve.v1.SpanLevel
}
var file_cognobserve_v1_ingest_proto_depIdxs = []int32{
	8,  // 0: cognobserve.v1.UserInfo.metadata:type_name -> google.protobuf.Struct
	8,  // 1: cognobserve.v1.IngestTraceRequest.metadata:type_name -> google.protobuf.Struct
	2,  // 2: cognobserve.v1.IngestTraceRequest.spans:type_name -> cognobserve.v1.IngestSpan
	0,  // 3: cognobserve.v1.IngestTraceRequest.user:type_name -> cognobserve.v1.UserInfo
	9,  // 4: cognobserve.v1.IngestSpan.start_time:type_name -> google.protobuf.Timestamp
	9,  // 5: cognobserve.v1.IngestSpan.end_time:type_name -> google.protobuf.Timestamp
	8,  // 6: cognobserve.v1.IngestSpan.input:type_name -> google.protobuf.Struct
	8,  // 7: cognobserve.v1.IngestSpan.output:type_name -> google.protobuf.Struct
	8,  // 8: cognobserve.v1.IngestSpan.metadata:type_name -> google.protobuf.Struct
	8,  // 9: cognobserve.v1.IngestSpan.model_parameters:type_name -> google.protobuf.Struct
	10, // 10: cognobserve.v1.IngestSpan.usage:type_name -> cognobserve.v1.TokenUsage
	11, // 11: cognobserve.v1.IngestSpan.level:type_name -> cognobserve.v1.SpanLevel
	1,  // 12: cognobserve.v1.IngestBatchRequest.traces:type_name -> cognobserve.v1.IngestTraceRequest
	3,  // 13: cognobserve.v1.IngestBatchResponse.results:type_name -> cognobserve.v1.IngestTraceResponse
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_cognobserve_v1_ingest_proto_init() }
func file_cognobserve_v1_ingest_proto_init() {
	if File_cognobserve_v1_ingest_proto != nil {
		return
	}
	file_cognobserve_v1_common_proto_init()
	file_cognobserve_v1_ingest_proto_msgTypes[0].OneofWrappers = []any{}
	file_cognobserve_v1_ingest_proto_msgTypes[1].OneofWrappers = []any{}
	file_cognobserve_v1_ingest_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cognobserve_v1_ingest_proto_rawDesc), len(file_cognobserve_v1_ingest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cognobserve_v1_ingest_proto_goTypes,
		DependencyIndexes: file_cognobserve_v1_ingest_proto_depIdxs,
		MessageInfos:      file_cognobserve_v1_ingest_proto_msgTypes,
	}.Build()
	File_cognobserve_v1_ingest_proto = out.File
	file_cognobserve_v1_ingest_proto_goTypes = nil
	file_cognobserve_v1_ingest_proto_depIdxs = nil
}
