// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: cognobserve/v1/trace.proto

package cognobservev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Trace represents a single request/operation flow
type Trace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,5,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trace) Reset() {
	*x = Trace{}
	mi := &file_cognobserve_v1_trace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trace) ProtoMessage() {}

func (x *Trace) ProtoReflect() protoreflect.Message {
	mi := &file_cognobserve_v1_trace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trace.ProtoReflect.Descriptor instead.
func (*Trace) Descriptor() ([]byte, []int) {
	return file_cognobserve_v1_trace_proto_rawDescGZIP(), []int{0}
}

func (x *Trace) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Trace) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Trace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Trace) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Trace) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Span represents an individual operation within a trace
type Span struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TraceId         string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	ParentSpanId    *string                `protobuf:"bytes,3,opt,name=parent_span_id,json=parentSpanId,proto3,oneof" json:"parent_span_id,omitempty"`
	Name            string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	StartTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3,oneof" json:"end_time,omitempty"`
	Input           *structpb.Struct       `protobuf:"bytes,7,opt,name=input,proto3,oneof" json:"input,omitempty"`
	Output          *structpb.Struct       `protobuf:"bytes,8,opt,name=output,proto3,oneof" json:"output,omitempty"`
	Metadata        *structpb.Struct       `protobuf:"bytes,9,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	Model           *string                `protobuf:"bytes,10,opt,name=model,proto3,oneof" json:"model,omitempty"`
	ModelParameters *structpb.Struct       `protobuf:"bytes,11,opt,name=model_parameters,json=modelParameters,proto3,oneof" json:"model_parameters,omitempty"`
	Usage           *TokenUsage            `protobuf:"bytes,12,opt,name=usage,proto3,oneof" json:"usage,omitempty"`
	Level           SpanLevel              `protobuf:"varint,13,opt,name=level,proto3,enum=cognobserve.v1.SpanLevel" json:"level,omitempty"`
	StatusMessage   *string                `protobuf:"bytes,14,opt,name=status_message,json=statusMessage,proto3,oneof" json:"status_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Span) Reset() {
	*x = Span{}
	mi := &file_cognobserve_v1_trace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Span) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Span) ProtoMessage() {}

func (x *Span) ProtoReflect() protoreflect.Message {
	mi := &file_cognobserve_v1_trace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Span.ProtoReflect.Descriptor instead.
func (*Span) Descriptor() ([]byte, []int) {
	return file_cognobserve_v1_trace_proto_rawDescGZIP(), []int{1}
}

func (x *Span) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Span) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Span) GetParentSpanId() string {
	if x != nil && x.ParentSpanId != nil {
		return *x.ParentSpanId
	}
	return ""
}

func (x *Span) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Span) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Span) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *Span) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *Span) GetOutput() *structpb.Struct {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *Span) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Span) GetModel() string {
	if x != nil && x.Model != nil {
		return *x.Model
	}
	return ""
}

func (x *Span) GetModelParameters() *structpb.Struct {
	if x != nil {
		return x.ModelParameters
	}
	return nil
}

func (x *Span) GetUsage() *TokenUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *Span) GetLevel() SpanLevel {
	if x != nil {
		return x.Level
	}
	return SpanLevel_SPAN_LEVEL_UNSPECIFIED
}

func (x *Span) GetStatusMessage() string {
	if x != nil && x.StatusMessage != nil {
		return *x.StatusMessage
	}
	return ""
}

// Project container
type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_cognobserve_v1_trace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_cognobserve_v1_trace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_cognobserve_v1_trace_proto_rawDescGZIP(), []int{2}
}

func (x *Project) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Project) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// API Key for authentication
type ApiKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	DisplayKey    string                 `protobuf:"bytes,3,opt,name=display_key,json=displayKey,proto3" json:"display_key,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_used_at,json=lastUsedAt,proto3,oneof" json:"last_used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKey) Reset() {
	*x = ApiKey{}
	mi := &file_cognobserve_v1_trace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKey) ProtoMessage() {}

func (x *ApiKey) ProtoReflect() protoreflect.Message {
	mi := &file_cognobserve_v1_trace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKey.ProtoReflect.Descriptor instead.
func (*ApiKey) Descriptor() ([]byte, []int) {
	return file_cognobserve_v1_trace_proto_rawDescGZIP(), []int{3}
}

func (x *ApiKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApiKey) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ApiKey) GetDisplayKey() string {
	if x != nil {
		return x.DisplayKey
	}
	return ""
}

func (x *ApiKey) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ApiKey) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

var File_cognobserve_v1_trace_proto protoreflect.FileDescriptor

const file_cognobserve_v1_trace_proto_rawDesc = "" +
	"\n" +
	"\x1acognobserve/v1/trace.proto\x12\x0ecognobserve.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bcognobserve/v1/common.proto\"\xcb\x01\n" +
	"\x05Trace\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x128\n" +
	"\bmetadata\x18\x05 \x01(\v2\x17.google.protobuf.StructH\x00R\bmetadata\x88\x01\x01B\v\n" +
	"\t_metadata\"\x81\x06\n" +
	"\x04Span\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12)\n" +
	"\x0eparent_span_id\x18\x03 \x01(\tH\x00R\fparentSpanId\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12:\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\aendTime\x88\x01\x01\x122\n" +
	"\x05input\x18\a \x01(\v2\x17.google.protobuf.StructH\x02R\x05input\x88\x01\x01\x124\n" +
	"\x06output\x18\b \x01(\v2\x17.google.protobuf.StructH\x03R\x06output\x88\x01\x01\x128\n" +
	"\bmetadata\x18\t \x01(\v2\x17.google.protobuf.StructH\x04R\bmetadata\x88\x01\x01\x12\x19\n" +
	"\x05model\x18\n" +
	" \x01(\tH\x05R\x05model\x88\x01\x01\x12G\n" +
	"\x10model_parameters\x18\v \x01(\v2\x17.google.protobuf.StructH\x06R\x0fmodelParameters\x88\x01\x01\x125\n" +
	"\x05usage\x18\f \x01(\v2\x1a.cognobserve.v1.TokenUsageH\aR\x05usage\x88\x01\x01\x12/\n" +
	"\x05level\x18\r \x01(\x0e2\x19.cognobserve.v1.SpanLevelR\x05level\x12*\n" +
	"\x0estatus_message\x18\x0e \x01(\tH\bR\rstatusMessage\x88\x01\x01B\x11\n" +
	"\x0f_parent_span_idB\v\n" +
	"\t_end_timeB\b\n" +
	"\x06_inputB\t\n" +
	"\a_outputB\v\n" +
	"\t_metadataB\b\n" +
	"\x06_modelB\x13\n" +
	"\x11_model_parametersB\b\n" +
	"\x06_usageB\x11\n" +
	"\x0f_status_message\"\xa3\x01\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe7\x01\n" +
	"\x06ApiKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x1f\n" +
	"\vdisplay_key\x18\x03 \x01(\tR\n" +
	"displayKey\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12A\n" +
	"\flast_used_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"lastUsedAt\x88\x01\x01B\x0f\n" +
	"\r_last_used_atB\xb5\x01\n" +
	"\x12com.cognobserve.v1B\n" +
	"TraceProtoP\x01Z:github.com/cognobserve/ingest/internal/proto/cognobservev1\xa2\x02\x03CXX\xaa\x02\x0eCognobserve.V1\xca\x02\x0eCognobserve\\V1\xe2\x02\x1aCognobserve\\V1\\GPBMetadata\xea\x02\x0fCognobserve::V1b\x06proto3"

var (
	file_cognobserve_v1_trace_proto_rawDescOnce sync.Once
	file_cognobserve_v1_trace_proto_rawDescData []byte
)

func file_cognobserve_v1_trace_proto_rawDescGZIP() []byte {
	file_cognobserve_v1_trace_proto_rawDescOnce.Do(func() {
		file_cognobserve_v1_trace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cognobserve_v1_trace_proto_rawDesc), len(file_cognobserve_v1_trace_proto_rawDesc)))
	})
	return file_cognobserve_v1_trace_proto_rawDescData
}

var file_cognobserve_v1_trace_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cognobserve_v1_trace_proto_goTypes = []any{
	(*Trace)(nil),                 // 0: cognobserve.v1.Trace
	(*Span)(nil),                  // 1: cognobserve.v1.Span
	(*Project)(nil),               // 2: cognobserve.v1.Project
	(*ApiKey)(nil),                // 3: cognobserve.v1.ApiKey
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 5: google.protobuf.Struct
	(*TokenUsage)(nil),            // 6: cognobserve.v1.TokenUsage
	(SpanLevel)(0),                // 7: cognobserve.v1.SpanLevel
}
var file_cognobserve_v1_trace_proto_depIdxs = []int32{
	4,  // 0: cognobserve.v1.Trace.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 1: cognobserve.v1.Trace.metadata:type_name -> google.protobuf.Struct
	4,  // 2: cognobserve.v1.Span.start_time:type_name -> google.protobuf.Timestamp
	4,  // 3: cognobserve.v1.Span.end_time:type_name -> google.protobuf.Timestamp
	5,  // 4: cognobserve.v1.Span.input:type_name -> google.protobuf.Struct
	5,  // 5: cognobserve.v1.Span.output:type_name -> google.protobuf.Struct
	5,  // 6: cognobserve.v1.Span.metadata:type_name -> google.protobuf.Struct
	5,  // 7: cognobserve.v1.Span.model_parameters:type_name -> google.protobuf.Struct
	6,  // 8: cognobserve.v1.Span.usage:type_name -> cognobserve.v1.TokenUsage
	7,  // 9: cognobserve.v1.Span.level:type_name -> cognobserve.v1.SpanLevel
	4,  // 10: cognobserve.v1.Project.created_at:type_name -> google.protobuf.Timestamp
	4,  // 11: cognobserve.v1.Project.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 12: cognobserve.v1.ApiKey.created_at:type_name -> google.protobuf.Timestamp
	4,  // 13: cognobserve.v1.ApiKey.last_used_at:type_name -> google.protobuf.Timestamp
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_cognobserve_v1_trace_proto_init() }
func file_cognobserve_v1_trace_proto_init() {
	if File_cognobserve_v1_trace_proto != nil {
		return
	}
	file_cognobserve_v1_common_proto_init()
	file_cognobserve_v1_trace_proto_msgTypes[0].OneofWrappers = []any{}
	file_cognobserve_v1_trace_proto_msgTypes[1].OneofWrappers = []any{}
	file_cognobserve_v1_trace_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cognobserve_v1_trace_proto_rawDesc), len(file_cognobserve_v1_trace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cognobserve_v1_trace_proto_goTypes,
		DependencyIndexes: file_cognobserve_v1_trace_proto_depIdxs,
		MessageInfos:      file_cognobserve_v1_trace_proto_msgTypes,
	}.Build()
	File_cognobserve_v1_trace_proto = out.File
	file_cognobserve_v1_trace_proto_goTypes = nil
	file_cognobserve_v1_trace_proto_depIdxs = nil
}
